# Site settings
title: GL_FragCoord.xy
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cuspace.github.io" # the base hostname & protocol for your site

excerpt_separator: ""

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: seeyouspace
  flickr:
  github: cuspace
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: seeyouspace
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks", "footnotes"]

disqus: cuspacegithubio
